print("Let's do something iconic!")
first_name = input('Tell me your first name: ')
last_name = input('Now tell me your last name: ')
print()
print('Your name is ' + last_name + ', ' + first_name + ' ' + last_name )